language: php

sudo: false

php:
    - 5.6
    - 7.0

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install --prefer-source

script:
    - make tests
