language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - 7.2

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then composer require --dev --no-update kphoen/rusty dev-master; fi
    - composer install --optimize-autoloader --no-interaction

script:
    - make tests
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then make rusty; fi
